pub struct SearchQuery {
    pub desired_skills: Vec<(Trait, u8)>,
    pub sigil_slots: u8,
}

pub struct SearchPool {
    pub sigils: Vec<Sigil>,
    pub wrightstones: Vec<Wrightstone>,
}

pub struct SearchResult {
    pub sigils: Vec<Sigil>,
    pub wrightstone: Option<Wrightstone>,
}

pub struct Sigil {
    pub level: u8,
    pub trait1: Trait,
    pub trait2: Option<Trait>,
}

pub struct Wrightstone {
    pub trait1: Trait,
    pub trait2: Option<Trait>,
    pub trait3: Option<Trait>,
    pub trait1_level: u8,
    pub trait2_level: u8,
    pub trait3_level: u8,
}

pub enum Trait {
    Aegis,
    ATK,
    ATKDownResistance,
    Autorevive,
    BlightResistance,
    BreakAssassin,
    BurnResistance,
    ButterflysGrace,
    Cascade,
    ChargedAttackDMG,
    ComboBooster,
    ComboFinisherDMG,
    ConcentratedFire,
    // CrabbyResonance,
    CriticalHitDMG,
    CriticalHitRate,
    DarkflameResistance,
    DEFDownDesistance,
    DMGCap,
    DizzyResistance,
    DodgePayback,
    DragonslayersDominance,
    Drain,
    EbonysPresence,
    Enmity,
    EternalRagesMettle,
    FastLearner,
    FearlessDrive,
    FirmStance,
    FoundersStrategy,
    Garrison,
    GlaciateResistance,
    GuardPayback,
    Guts,
    HeldUnderResistance,
    HerosCreed,
    HolyKnightsLuster,
    HP,
    ImprovedDodge,
    ImprovedGuard,
    ImprovedHealing,
    InjuryToInsult,
    LifeOnTheLine,
    LinkedTogether,
    LordsProcession,
    LowProfile,
    LuckyCharge,
    MagesAspiration,
    NimbleDefense,
    NimbleOnslaught,
    OverdriveAssassin,
    ParalysisResistance,
    PathToMastery,
    PhantasmsConcord,
    PotionHoarder,
    PreciseResilience,
    PreciseWrath,
    Provoke,
    QuickCharge,
    QuickCooldown,
    Regen,
    RosesBlooming,
    RupieTycoon,
    SandtombResistance,
    SkilledAssault,
    SlowResistance,
    Stamina,
    SteadyFocus,
    SteelNerves,
    StoutHeart,
    StunPower,
    SwordmastersProwess,
    ThrowDMG,
    Tyranny,
    Uplift,
    VeteransInsight,
    WeakPointDMG,
    WhiteDragonsOath,
}
